### ISSUE TITLE
Question with lpips results in your MCL-net  paper

### ISSUE THREAD

**Issue by mlyarthur** [fnzhan/UNITE#11]
![image](https://user-images.githubusercontent.com/29242717/176373863-6f96af86-578c-4e26-8204-abd8f6b5e4f6.png)
I have a question about your lpips score calculation. Should'nt lpips score is the lower the better? Does you adopt different metric calculation?

**Comment by fnzhan** [comment]
Here LPIPS is used to evaluate the diversity (not quality) of different exemplars.
