### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by Huage001** [fnzhan/UNITE#3]
Hi,

Thank you for your impressive work. 
It seems that there is something wrong with the link of pre-trained models. Could you please share them again?
Thanks for your efforts a lot.

**Comment by Huage001** [comment]
Thank you for your quick response! :)

**Comment by fido20160817** [comment]
Hi, where to download the pretrained model on deepfashion, coco and celeb? I just find ade20 on the provided link
